try cygwin install

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -5,173 +5,101 @@ on:
     tags:
     - 'v*.*.*'
     branches:
-      - pyvcf
+    - cygwin
   pull_request:
     branches:
-      - master
+    - master
 
 env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
-  linux_build:
-    name: Build linux and singularity image
-    runs-on: ubuntu-20.04
-    steps:
-
-    - name: Set up Go 1.16
-      uses: actions/setup-go@v1
-      with:
-        go-version: 1.16
-      id: go
-
-    - name: Install Dependencies
-      run: |
-        sudo apt-get update && sudo apt-get install -y \
-          build-essential \
-          libssl-dev \
-          uuid-dev \
-          libgpgme11-dev \
-          squashfs-tools \
-          libseccomp-dev \
-          pkg-config \
-          debootstrap \
-          debian-keyring \
-          debian-archive-keyring \
-          rsync
-
-    - name: Install Singularity
-      env:
-        SINGULARITY_VERSION: 3.5.3
-        GOPATH: /tmp/go
-      run: |
-        mkdir -p $GOPATH
-        sudo mkdir -p /usr/local/var/singularity/mnt
-        mkdir -p $GOPATH/src/github.com/sylabs
-        cd $GOPATH/src/github.com/sylabs
-        wget https://github.com/hpcng/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
-        tar -xzf singularity-${SINGULARITY_VERSION}.tar.gz
-        cd singularity
-        ./mconfig -v -p /usr/local
-        make -j `nproc 2>/dev/null || echo 1` -C ./builddir all
-        sudo make -C ./builddir install
-
-
-    - name: Check out code for the container build
-      uses: actions/checkout@v2
-
-    - name: Set release version if is a release
-      if: startsWith(github.event.ref, 'refs/tags/v')
-      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
-
-    - name: Set release version if not a release
-      if: false == startsWith(github.event.ref, 'refs/tags/v')
-      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
-
-    - name: Build Singularity container
-      env:
-        SINGULARITY_RECIPE: Singularity.def
-        OUTPUT_CONTAINER: mykrobe_${{env.RELEASE_VERSION}}.img
-      run: |
-        ls
-        if [ -f "${SINGULARITY_RECIPE}" ]; then
-            sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
-        else
-            echo "${SINGULARITY_RECIPE} is not found."
-            echo "Present working directory: $PWD"
-            ls
-        fi
-
-    - name: Release
-      if: startsWith(github.event.ref, 'refs/tags/v')
-      uses: softprops/action-gh-release@v1
-      with:
-        files: mykrobe*.img
-        draft: true
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-  mac_build:
-    name: Build mac os command line
-    runs-on: macos-11
-    steps:
-
-    - name: Install dependencies
-      run: |
-        pip3 install cython requests wheel tox pyinstaller
-
-    - name: Check out code for the build
-      uses: actions/checkout@v2
-
-    - name: Set release version if is a release
-      if: startsWith(github.event.ref, 'refs/tags/v')
-      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
-
-    - name: Set release version if not a release
-      if: false == startsWith(github.event.ref, 'refs/tags/v')
-      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
-
-    - name: Test and build command line tarball
-      env:
-        OUTPUT_TARBALL: mykrobe.command_line.osx.${{env.RELEASE_VERSION}}.tar.gz
-      run: |
-        # mongod default data directory is /data/db, which is not writeable.
-        mkdir $HOME/mongodb_data
-        chown -R `id -un` $HOME/mongodb_data
-        sudo mongod --dbpath=$HOME/mongodb_data --quiet &> /dev/null &
-        sleep 3s
-        rm -rf .tox
-        sudo tox
-        sudo pip3 install .
-        mykrobe panels update_metadata --panels_dir src/mykrobe/data
-        mykrobe panels update_species --panels_dir src/mykrobe/data --debug all
-        cd dist
-        pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
-        cd pyinstaller_build
-        tar cvfz ../../${OUTPUT_TARBALL} mykrobe_atlas/
-
-    - name: Release
-      if: startsWith(github.event.ref, 'refs/tags/v')
-      uses: softprops/action-gh-release@v1
-      with:
-        files: mykrobe.command_line.osx.*.tar.gz
-        draft: true
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-#  windows_build:
-#    name: Build Windows command line
-#    runs-on: windows-2019
+#  linux_build:
+#    name: Build linux and singularity image
+#    runs-on: ubuntu-20.04
 #    steps:
-#    - uses: msys2/setup-msys2@v2
+#
+#    - name: Set up Go 1.16
+#      uses: actions/setup-go@v1
 #      with:
-#        update: true
-#        install: >-
-#          autotools git gcc python python-pip python-devel python-setuptools zlib-devel libcurl-devel bzip2 liblzma zip libbz2-devel xz zlib zlib-devel libtool wget liblzma-devel ncurses-devel base-devel openssl-devel mingw64/mingw-w64-x86_64-python3 mingw64/mingw-w64-x86_64-python3-pip mingw-w64-x86_64-python-numpy mingw-w64-x86_64-python-setuptools
+#        go-version: 1.16
+#      id: go
+#
+#    - name: Install Dependencies
+#      run: |
+#        sudo apt-get update && sudo apt-get install -y \
+#          build-essential \
+#          libssl-dev \
+#          uuid-dev \
+#          libgpgme11-dev \
+#          squashfs-tools \
+#          libseccomp-dev \
+#          pkg-config \
+#          debootstrap \
+#          debian-keyring \
+#          debian-archive-keyring \
+#          rsync
+#
+#    - name: Install Singularity
+#      env:
+#        SINGULARITY_VERSION: 3.5.3
+#        GOPATH: /tmp/go
+#      run: |
+#        mkdir -p $GOPATH
+#        sudo mkdir -p /usr/local/var/singularity/mnt
+#        mkdir -p $GOPATH/src/github.com/sylabs
+#        cd $GOPATH/src/github.com/sylabs
+#        wget https://github.com/hpcng/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-${SINGULARITY_VERSION}.tar.gz
+#        tar -xzf singularity-${SINGULARITY_VERSION}.tar.gz
+#        cd singularity
+#        ./mconfig -v -p /usr/local
+#        make -j `nproc 2>/dev/null || echo 1` -C ./builddir all
+#        sudo make -C ./builddir install
+#
+#
+#    - name: Check out code for the container build
+#      uses: actions/checkout@v2
+#
+#    - name: Set release version if is a release
+#      if: startsWith(github.event.ref, 'refs/tags/v')
+#      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+#
+#    - name: Set release version if not a release
+#      if: false == startsWith(github.event.ref, 'refs/tags/v')
+#      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
+#
+#    - name: Build Singularity container
+#      env:
+#        SINGULARITY_RECIPE: Singularity.def
+#        OUTPUT_CONTAINER: mykrobe_${{env.RELEASE_VERSION}}.img
+#      run: |
+#        ls
+#        if [ -f "${SINGULARITY_RECIPE}" ]; then
+#            sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
+#        else
+#            echo "${SINGULARITY_RECIPE} is not found."
+#            echo "Present working directory: $PWD"
+#            ls
+#        fi
+#
+#    - name: Release
+#      if: startsWith(github.event.ref, 'refs/tags/v')
+#      uses: softprops/action-gh-release@v1
+#      with:
+#        files: mykrobe*.img
+#        draft: true
+#      env:
+#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#
+#  mac_build:
+#    name: Build mac os command line
+#    runs-on: macos-11
+#    steps:
 #
 #    - name: Install dependencies
 #      run: |
-#        echo "which docker"
-#        docker --help
-#        docker pull ghcr.io/white-gecko/docker-pyinstaller:feature-buildWithGA-py3-win64
-#        docker run 82c0952068e2
-#        exit
-#        C:\\msys64\\mingw64\\bin\\python3.exe -m ensurepip
-#        C:\\msys64\\mingw64\\bin\\python3.exe -m pip -v install six
-#        #C:\\msys64\\mingw64\\bin\\python3.exe -m pip -v install --upgrade setuptools
-#        C:\\msys64\\mingw64\\bin\\python3.exe -m pip -v install "pefile>=2021.9.3" "pywin32-ctypes>=0.2.0"
-#        C:\\msys64\\mingw64\\bin\\python3.exe -m pip -v install "pyinstaller>=4.10"
-#        C:\\msys64\\mingw64\\bin\\python3.exe -m pip -v install wheel
-#        C:\\msys64\\mingw64\\bin\\python3.exe -m pip -v install tox requests
-#        /usr/bin/python3 -m pip install wheel
-#        /usr/bin/python3 -m pip install "cython>=0.29.28" requests tox "pefile>=2021.9.3" "pywin32-ctypes>=0.2.0"
-#        echo "/usr/bin/python3 -m pip install pyinstaller"
-#        /usr/bin/python3 -m pip install pyinstaller
-#        echo "which pyinstaller"
-#        which pyinstaller
-#
-#      shell: msys2 {0}
+#        pip3 install cython requests wheel tox pyinstaller
 #
 #    - name: Check out code for the build
 #      uses: actions/checkout@v2
@@ -179,13 +107,86 @@ jobs:
 #    - name: Set release version if is a release
 #      if: startsWith(github.event.ref, 'refs/tags/v')
 #      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
-#      shell: msys2 {0}
 #
 #    - name: Set release version if not a release
 #      if: false == startsWith(github.event.ref, 'refs/tags/v')
 #      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
-#      shell: msys2 {0}
 #
+#    - name: Test and build command line tarball
+#      env:
+#        OUTPUT_TARBALL: mykrobe.command_line.osx.${{env.RELEASE_VERSION}}.tar.gz
+#      run: |
+#        # mongod default data directory is /data/db, which is not writeable.
+#        mkdir $HOME/mongodb_data
+#        chown -R `id -un` $HOME/mongodb_data
+#        sudo mongod --dbpath=$HOME/mongodb_data --quiet &> /dev/null &
+#        sleep 3s
+#        rm -rf .tox
+#        sudo tox
+#        sudo pip3 install .
+#        mykrobe panels update_metadata --panels_dir src/mykrobe/data
+#        mykrobe panels update_species --panels_dir src/mykrobe/data --debug all
+#        cd dist
+#        pyinstaller --workpath='./pyinstaller_build/binary_cache' --distpath='./pyinstaller_build' mykrobe_atlas_pyinstaller.spec
+#        cd pyinstaller_build
+#        tar cvfz ../../${OUTPUT_TARBALL} mykrobe_atlas/
+#
+#    - name: Release
+#      if: startsWith(github.event.ref, 'refs/tags/v')
+#      uses: softprops/action-gh-release@v1
+#      with:
+#        files: mykrobe.command_line.osx.*.tar.gz
+#        draft: true
+#      env:
+#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  windows_build:
+    name: Build Windows command line
+    runs-on: windows-2019
+    steps:
+    #- uses: msys2/setup-msys2@v2
+    #  with:
+    #    update: true
+    #    install: >-
+    #      autotools git gcc python python-pip python-devel python-setuptools zlib-devel libcurl-devel bzip2 liblzma zip libbz2-devel xz zlib zlib-devel libtool wget liblzma-devel ncurses-devel base-devel openssl-devel mingw64/mingw-w64-x86_64-python3 mingw64/mingw-w64-x86_64-python3-pip mingw-w64-x86_64-python-numpy mingw-w64-x86_64-python-setuptools
+
+    - name: Set up Cygwin
+      uses: egor-tensin/setup-cygwin@v3
+      with:
+        platform: x64
+        packages: make,unzip,automake,automake1.16,autoconf,autoconf2.5,zip,libbz2-devel,bzip2,xz,zlib,zlib-devel,python3,libtool,wget,liblzma-devel,libcurl-devel,R,libncurses-devel,python3-cython,python3-devel
+
+    - name: Install dependencies
+      run: |
+		echo "which python"
+        which python
+		echo "which python3"
+        which python3
+		python3 -m pip install --upgrade pip
+		git clone --recursive -b geno_kmer_count https://github.com/phelimb/mccortex
+		cd mccortex/libs/htslib && git checkout bcf9bff178f81c9c1cf3a052aeb6cbe32fe5fdcc
+		cd mccortex/libs/bcftools && git checkout b406a3906b153faa8bec0a53df07b2adf18a3052
+		cd mccortex/libs/samtools && git checkout 2d4907cf9a34ccf7cde60143158b39e1cb40ac0c
+		python3 ./ci/windows_file_fixes.py
+		cd mccortex && make all && make tests
+		pip3 install wheel
+		pip3 install tox requests numpy==1.15
+
+      shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
+
+    - name: Check out code for the build
+      uses: actions/checkout@v2
+
+    - name: Set release version if is a release
+      if: startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
+      shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
+
+    - name: Set release version if not a release
+      if: false == startsWith(github.event.ref, 'refs/tags/v')
+      run: echo "RELEASE_VERSION=test" >> $GITHUB_ENV
+      shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
+
 #    - name: Test and build command line tarball
 #      env:
 #        OUTPUT_TARBALL: mykrobe.command_line.windows.${{env.RELEASE_VERSION}}.tar.gz
@@ -237,4 +238,4 @@ jobs:
 #        draft: true
 #      env:
 #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-#
+
